### ISSUE TITLE
Cannot GET index.html 

### ISSUE THREAD

**Issue by newcanopies** [jarden-liu/node-webkit-webpack-starter#1]

**Comment by jardenliu** [comment]
This repo has not been used for a long time. Maybe Electron is better choise for you.

**Comment by newcanopies** [comment]
hi @jarden-liu, 

the advantage of NWjs is using the app in the web browser directly, while wrapping some cpp based node_modules so they can be used client side.

**Comment by jardenliu** [comment]
If this repo can help you, fork it and fix it for youself
